# Roundcube mail setup!

- name: Prepare chroot for usage with TLS
  command: mkdir -p /var/www/etc/ssl

- name: Prepare chroot for usage with TLS
  command: install -m 444 -o root -g bin /etc/ssl/cert.pem /etc/ssl/openssl.cnf /var/www/etc/ssl/

- name: Copy php-fpm.conf to /etc/
  copy:
    src: files/php-fpm.conf
    dest: /etc/php-fpm.conf
    mode: "0600"
  tags: roundcubemail

- name: Creating initial database
  command: mysql_install_db

- name: Enable mysqld
  command: rcctl enable mysqld

- name: Start mysqld
  command: rcctl start mysqld

# Don't forget to add setup of mysql_secure_installation script here.

- name: Allow access from chroot to mysql databse
  command: install -d -m 0711 -o _mysql -g _mysql /var/www/var/run/mysql

- name: Copy my.cnf to /etc/
  copy:
    src: files/my.cnf
    dest: /etc/my.cnf
    mode: "0600"
  tags: roundcubemail