---
# Tasks file for httpd

- name: Touch /etc/httpd.conf to add the file if it doesnt exist
  ansible.builtin.file:
    path: /etc/httpd.conf
    state: touch
    mode: u=rw,g=r,o=r

- name: Template /etc/httpd.conf
  template:
    src: templates/httpd.j2
    dest: /etc/httpd.conf
    mode: "0600"
  tags: httpd

- name: Create /mta-sts directory
  ansible.builtin.file:
    path: /var/www/mta-sts
    state: directory
    mode: '0755'

- name: Template /var/www/mta-sts/mta-sts.txt
  template:
    src: templates/mta-sts.j2
    dest: /var/www/mta-sts/mta-sts.txt
    mode: "0755"
  tags: httpd

- name: Enable httpd
  command: rcctl enable httpd

- name: Start httpd
  command: rcctl start httpd
